#!/bin/bash

t2() {
for ((i=1;i<13;i++))
  do 
    resl2=$[a+=2]
   echo "2 * $i = $resl2"
   
done
}
t3() {
for ((i=1;i<13;i++))
  do 
    resl3=$[b+=2]
   echo "3 * $e = $resl3"
   
done
}

t4() {
for ((i=1;i<13;i++))
  do 
    resl4=$[c+=2]
   echo "4 * $i=$resl4"
   
done
}

t5() {
for ((i=1;i<13;i++))
  do 
    resl5=$[d+=2]
   echo "5 * $i = $resl5"
   
done
}

t6() {
for ((i=1;i<13;i++))
  do 
    resl6=$[e+=2]
   echo "2 * $i = $resl6"
   
done
}

t7() {
for ((i=1;i<13;i++))
  do 
    resl7=$[f+=2]
   echo "2 * $i = $resl7"
   
done
}

t8() {
for ((i=1;i<13;i++))
  do 
    resl8=$[g+=2]
   echo "2 * $i = $resl8"
   
done
}

t9() {
for ((i=1;i<13;i++))
  do 
    resl9=$[h+=2]
   echo "2 * $i = $resl9"
   
done
}

t10() {
for ((i=1;i<13;i++))
  do 
    resl10=$[i+=2]
   echo "2 * $i = $resl10"
   
done
}

t11() {
for ((i=1;i<13;i++))
  do 
    resl11=$[j+=2]
   echo "2 * $i = $resl11"
   
done
}

t12() {
for ((q=1;q<13;q++))
  do 
    resl12=$[h+=12]
   echo "12 * $q = $resl12"
   
done
} 
t2
echo ""
t3
echo ""
t4
echo ""
t5
echo ""
t6
echo ""
t7
echo ""
t8
echo ""
t9
echo ""
t10
echo ""
t11
echo ""
t12
echo ""
